# Generated by Django 4.1 on 2022-08-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_number",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Numer pojazdu"
                    ),
                ),
                (
                    "car_mileage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Przebieg"
                    ),
                ),
                (
                    "car_service_inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data przeglądu serwisowego"
                    ),
                ),
                (
                    "car_technical_inspection_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data przeglądu technicznego",
                    ),
                ),
                (
                    "car_content",
                    models.TextField(blank=True, null=True, verbose_name="opis"),
                ),
            ],
        ),
    ]
