# Generated by Django 4.1 on 2022-08-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_service_inspection_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_technical_inspection_date',
            field=models.DateField(blank=True),
        ),
    ]
