# Generated by Django 4.1 on 2022-08-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Marka i model",
            ),
        ),
    ]
