# Generated by Django 4.1 on 2022-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_car_service_inspection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_content',
            field=models.TextField(blank=True),
        ),
    ]
