# Generated by Django 4.1 on 2022-08-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_car_content_alter_car_car_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_content',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_service_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data przeglądu serwisowego'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_technical_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data przeglądu technicznego'),
        ),
    ]
