# Generated by Django 4.1 on 2022-08-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_car_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_technical_inspection_date',
            field=models.DateField(blank=True, help_text='Uzyj formatu: <em>YYYY-MM-DD</em>', null=True, verbose_name='Data przeglądu technicznego'),
        ),
    ]
